// Default (English) labels. Hosts pass a translated `labels` object (lang/*/composer.php) that is merged over these.
export const LABELS = {
    placeholder: 'Message',
    send: 'Send', undo: 'Undo send', attach: 'Attach', emoji: 'Emoji', gif: 'GIF', schedule: 'Schedule send', record: 'Record a voice note',
    searchEmoji: 'Search emojis…', recent: 'Recent', noEmoji: 'No emoji found',
    gallery: 'Gallery', camera: 'Camera', video: 'Video', document: 'Document', audio: 'Audio', location: 'Location', contact: 'Contact', poll: 'Poll',
    recentPhotos: 'Recent photos',
    searchGifs: 'Search my GIFs by name', imagesToGif: 'Images → GIF', videoToGif: 'Video clip → GIF',
    noGifs: 'No saved GIFs yet. Make one from 2–7 images or a video clip.', noGifNamed: 'No GIF named “{q}”', fromWeb: 'From the web',
    gifNeedImages: 'Choose 2 to 7 images. You chose {n}.', timePerImage: 'Time per image', saveGif: 'Save to my GIFs', nameGif: 'Name it, e.g. thank you dance',
    building: 'Building…', frame: 'Frame {n}', gifFailed: 'Couldn’t build that GIF. Try smaller files.', gifSaved: 'Saved “{name}”. Tap it in GIF to send.', gifStorage: 'Couldn’t save. Browser storage is full.',
    rename: 'Rename', del: 'Delete', cancel: 'Cancel', save: 'Save', ok: 'OK', remove: 'Remove', dismiss: 'Dismiss', retry: 'Retry',
    renameGif: 'Rename GIF', deleteGif: 'Delete “{name}”?', start: 'Start', end: 'End', startNow: 'Start = now', endNow: 'End = now',
    contactName: 'Name', contactPhone: 'Phone number', addContact: 'Add contact',
    pollQuestion: 'Ask a question', pollOption: 'Option {n}', addOption: '+ Add option', createPoll: 'Create poll',
    scheduleAt: 'Deliver at', scheduleSet: 'Will deliver {when}', scheduleCleared: 'Schedule cleared.', scheduleInvalid: 'That time isn’t valid or is in the past.', setSchedule: 'Set time', clearSchedule: 'Clear',
    locationAsk: 'Share your location', locationLive: 'Live for 15 minutes', locationPin: 'One-time pin', locationUnavailable: 'Location isn’t available in this browser.', locationDenied: 'Couldn’t get your location. Check permissions.', liveTag: 'Live 15m · ',
    caption: 'Caption applies to all', original: 'View original',
    sent: 'Sent', queued: 'Message queued.', offline: 'You’re offline. Message queued; it retries automatically.', backOnline: 'Back online. Sending queued messages.',
    offlineCount: 'Offline. {n} queued, will retry.', scheduled: 'Scheduled for {when}', scheduledOk: 'Scheduled. Your server will deliver it.', cancelled: 'Send cancelled. Your message is back.',
    failed: 'Couldn’t send ({err}). Retrying shortly.', failedFinal: 'Message failed to send ({err}).', restored: 'Restored {n} unsent message(s).',
    draftOld: 'Unsent draft from {n} day(s) ago.', discard: 'Discard', draftOther: 'You have a draft on another screen.', pickUp: 'Pick up',
    sentBefore: 'You sent “{name}” {when} too.', theySent: 'They already sent you “{name}” {when}.', today: 'earlier today', onDay: 'on {day}',
    hintMean: 'Did you mean “{fix}”?', hintFix: 'Fix', hintLink: 'This link hides or disguises its destination. Check it before sending.',
    micPrimer: 'We need microphone access to record your voice note.', micPrimerSub: 'Your browser will ask next. Nothing is recorded until you tap record.', micAllow: 'Allow microphone', micNotNow: 'Not now',
    micDenied: 'Microphone access is blocked. Enable it for this site in your browser settings, then tap the mic again. You can still type or attach a file.',
    micUnsupported: 'Recording isn’t supported in this browser. You can still type or attach a file.', micError: 'Something went wrong recording. Please try again, or type your message instead.',
    pause: 'Pause', resume: 'Resume', discardVoice: 'Discard voice note', sendVoice: 'Send voice note', playPreview: 'Play preview', speed: 'Playback speed',
    listening: 'Listening…', noCaptions: 'Live captions aren’t supported in this browser.', sendingVoice: 'Sending voice note…', voiceNote: 'Voice note', voiceReady: 'Voice note ready',
    tooMany: 'You can attach up to {n} file(s).', tooBig: '“{name}” is larger than {mb} MB.', badType: '“{name}” isn’t a supported file type.',
    addr: 'Save your address for /addr', typeMessage: 'Message',
};

export const fmt = (s, vars = {}) => String(s).replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? ''));
